name: joystick
description: Joystickli mini bir galeri [Flutter]

publish_to: 'none' 
version: 1.0.0+1
author: yepyepunibel
homepage: https://github.com/yepyepunibel/
repository: https://github.com/yepyepunibel/joystickli-flutter-galerisi
documentation: https://github.com/yepyepunibel/joystickli-flutter-galerisi

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true

 